services:
  etcd:
    image: registry.k8s.io/etcd:3.5.12-0
    container_name: apisix-etcd
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    command: ["etcd"]

  apisix-testing-environment:
    network_mode: "service:etcd"
    build:
      context: ${SIXTE_HOME:-.}
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}
    container_name: ${SIXTE_NAME}
    volumes:
      - ${PROJECT_DIR:-.}/apisix/plugins/:/opt/custom-plugins/apisix/plugins/
      - ${PROJECT_DIR:-.}/t:/apisix/t
    working_dir: /usr/local/apisix-src
